// <auto-generated />
using Empleados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Empleados.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20190725171029_clientspaymentsrecordsportFolio")]
    partial class clientspaymentsrecordsportFolio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Empleados.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<string>("applealed");

                    b.Property<string>("name");

                    b.Property<string>("other");

                    b.Property<string>("photo");

                    b.Property<string>("telephone");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Empleados.Models.Employe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<string>("applealed");

                    b.Property<string>("name");

                    b.Property<string>("photo");

                    b.Property<string>("telephone");

                    b.HasKey("id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Empleados.Models.IdRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Status");

                    b.Property<int>("idParameter");

                    b.Property<int>("idREcord");

                    b.HasKey("id");

                    b.ToTable("Foliados");
                });

            modelBuilder.Entity("Empleados.Models.Payments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("idClient");

                    b.Property<int>("idEmploye");

                    b.Property<double>("newBalance");

                    b.Property<double>("payment");

                    b.Property<double>("preBalance");

                    b.HasKey("id");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Empleados.Models.PortFolio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdClient");

                    b.Property<bool>("Status");

                    b.Property<double>("Total");

                    b.Property<int>("idEmploye");

                    b.HasKey("id");

                    b.ToTable("Carteras");
                });
#pragma warning restore 612, 618
        }
    }
}
