// <auto-generated />
using System;
using Empleados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Empleados.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Empleados.Models.Access", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Employeid");

                    b.Property<string>("menu");

                    b.Property<bool>("status");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.HasIndex("Employeid");

                    b.ToTable("Access");
                });

            modelBuilder.Entity("Empleados.Models.Employe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Empleados.Models.Access", b =>
                {
                    b.HasOne("Empleados.Models.Employe")
                        .WithMany("accesss")
                        .HasForeignKey("Employeid");
                });
#pragma warning restore 612, 618
        }
    }
}
